[package]
name = "echo-dylib-filter"
version = "0.1.0"
edition = "2021"

[lib]
name = "echo"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
